---
title: "Preprocesamiento"
subtitle: "Master de Big Data"
author: "José Tomás Palma Méndez"
date: '`r format(Sys.Date(), "%e de %B de %Y")`'
output:
   html_document:
     number_sections: yes
     toc: true
     toc_depth: 3
     toc_float: true
lang: es
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center", results = "hide")

# Establecer el directorio de trabajo
if (interactive()) {
  setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
}

# Cargamos las librerías necesarias
library(caret)
```

```{r}
# Leemos los datos
hepatitis.KnnImp <- read.csv(
  "Datos/hepatitisKnnImp.csv",
  header = TRUE,
  stringsAsFactors = TRUE
)

# Vemos los datos
str(hepatitis.KnnImp)
```

```{r}
# Realizamos un gráfico de parejas (pairplor)
plot.columns <- c("BILIRRUBINA", "FOSFATOalc", "SGOT", "ALBUMINA")
featurePlot(
  x = hepatitis.KnnImp[, (names(hepatitis.KnnImp) %in% plot.columns)],
  y = hepatitis.KnnImp$PRONOSTICO,
  plot = "pairs",
  auto.key = list(columns = 2)
)
```

```{r}
# Dividimos los conjuntos en train y test
set.seed(342)

trainIndex <- createDataPartition(
  hepatitis.KnnImp$PRONOSTICO,
  p = 0.66,
  list = FALSE,
  times = 1
)
```

```{r}
# Hacemos un análisis por PCA

``````